### ISSUE TITLE
Moodle coding convention

### ISSUE THREAD

**Issue by mchurchward** [telabotanica/moodle-block_completeyourprofile#2]
Hi.
As part of approving your plugin entry at the Moodle plugins database, it is encouraged to follow Moodle’s coding style as outlined in: http://docs.moodle.org/dev/Coding_style and http://docs.moodle.org/dev/Coding. The code checker plugin can be quite helpful in fine tuning your code and can be found at: https://moodle.org/plugins/view.php?plugin=local_codechecker You may wish to consider using that tool to further improve your plugin.
Since you are using Github, it may be easier to set up Travis CI to do the testing for you. See this forum post for details - https://moodle.org/mod/forum/discuss.php?d=323384

**Comment by matcho** [comment]
Hi.
Thanks a lot for this precise advice, I'll try this quickly.

**Comment by mchurchward** [comment]
No problem. If you wish to see the results of the Tavis CI test, I have run them here for two different versions of PHP and two database technologies - https://travis-ci.org/POETGroup/moodle-block_completeyourprofile/builds/125828946

**Comment by matcho** [comment]
Thanks. I added a Travis CI config for this repo, using https://github.com/moodlerooms/moodle-plugin-ci - the versions matrix is minimal at the moment, but it helped with Moodle coding style, which should be OK now. The build status can be seen at the bottom of the REAME.md
