### ISSUE TITLE
Plugins guardians review comments

### ISSUE THREAD

**Issue by mchurchward** [telabotanica/moodle-block_completeyourprofile#4]
Hi -
As part of the peer review for the plugins database, here are some suggested changes:
1) In block_completeyourprofile::generate_content, there is a check for a guest users using "$USER->id == 1". It would be better to use the Moodle API's to check this. I suggest using:
    "if (!isloggedin() or isguestuser()) {"
instead.
2) The block is set up such that each instance of the block is configured with how it deals with profile settings. Is this the intent? It seems like this would be something set for all block instances at the main block configuration. If you meant the former, that's fine, and you may want to change your description to described that every instance of the block will need to be configured. But if you meant for the settings to be consistent for all blocks, consider adding a global setting function for the block.

Thanks for your submission!

**Comment by matcho** [comment]
Hi.
1) fixed at 5a658fe
2) you're right, it was not the intent; will fix this asap

Thanks for your review !

**Comment by matcho** [comment]
Switched from local config to global config at 41b0606
